points:
  1: {x: -1.3830907344818115, y: -0.22563070058822632, z: 0.002471923828125}
  2: {x:  1.2793023586273193, y: -0.06741441786289215, z: 0.0025634765625}
  3: {x: -0.023289239034056664, y: -1.0942282676696777, z: -0.001434326171875}
  4: {x: -0.0026952694170176983, y:  1.0242401361465454, z: 0.002471923828125}
  5: {x: -1.5400662422180176, y:  1.0453156232833862, z: -0.001434326171875}

# 중앙 경유 정책 파라미터
frame_id: "map"
center_x: 0.0          # 항상 x=0.0 세로축을 경유
goal_tolerance_xy: 0.2 # (선택) 도착 판정 여유
goal_tolerance_yaw: 0.3
marker_scale: 0.2      # RViz 마커 텍스트 크기
